name = "ai-layoff-tracker"
main = "src/worker.js"
compatibility_date = "2026-01-01"

[assets]
directory = "./public"

[[kv_namespaces]]
binding = "SUBMISSIONS"
id = "620a98c11c0d40eab3c9f84c145a1d9e"
