#!/usr/bin/env python3
"""
Multilingual Page Generator - AI Layoff Tracker
=================================================
Reads public/index.html (English, generated by generate_page.py) and produces:
  public/zh-hans/index.html  — Simplified Chinese
  public/zh-hant/index.html  — Traditional Chinese
  public/es/index.html       — Spanish

Run this script AFTER generate_page.py:
  python scripts/generate_page.py
  python scripts/generate_i18n.py

Only the UI chrome is translated. The ALL_EVENTS data (company names, notes,
dates, source URLs) stays in English — these are factual records, not UI text.

The language switcher (EN | 简 | 繁 | ES) is already added to public/index.html
by generate_page.py. This script adds it to each translated page as well, with
the appropriate active language highlighted.
"""

import os
import re


# ─── Shared CSS and hreflang ────────────────────────────────────────────────

HREFLANG_BLOCK = """    <link rel="alternate" hreflang="en" href="https://layoffs.eudy.co/">
    <link rel="alternate" hreflang="zh-Hans" href="https://layoffs.eudy.co/zh-hans/">
    <link rel="alternate" hreflang="zh-Hant" href="https://layoffs.eudy.co/zh-hant/">
    <link rel="alternate" hreflang="es" href="https://layoffs.eudy.co/es/">
    <link rel="alternate" hreflang="x-default" href="https://layoffs.eudy.co/">"""


def build_switcher(active_code):
    """Return the lang switcher <nav> HTML with the correct active item."""
    langs = [
        ("EN",  "/",          "en"),
        ("简",  "/zh-hans/",  "zh-hans"),
        ("繁",  "/zh-hant/",  "zh-hant"),
        ("ES",  "/es/",       "es"),
    ]
    items = []
    for i, (label, href, code) in enumerate(langs):
        cls = "lang-btn lang-active" if code == active_code else "lang-btn"
        items.append(f'        <a href="{href}" class="{cls}">{label}</a>')
        if i < len(langs) - 1:
            items.append('        <span class="lang-sep">|</span>')
    inner = "\n".join(items)
    return f'    <nav class="lang-switcher">\n{inner}\n    </nav>'


def transform(base_html, lang_code, lang_attr, translations, regex_translations):
    """
    Apply all transformations to the English base HTML:
      1. Set <html lang="...">
      2. Replace hreflang block (already in base from generate_page.py)
      3. Swap lang switcher active item
      4. Apply UI string translations
      5. Apply regex translations for strings that embed daily-changing numbers
    """
    html = base_html

    # 1. html lang attribute
    html = re.sub(r'<html lang="[^"]*">', f'<html lang="{lang_attr}">', html, count=1)

    # 2. hreflang block is already present; no change needed (same for all pages)

    # 3. Replace the lang switcher nav with one that highlights the correct language
    html = re.sub(
        r'<nav class="lang-switcher">.*?</nav>',
        build_switcher(lang_code),
        html,
        count=1,
        flags=re.DOTALL,
    )

    # 4. UI string translations
    for old, new in translations:
        html = html.replace(old, new)

    # 5. Regex translations — the number is generated fresh each day, so it must
    #    be captured and carried into the translation, never hardcoded in a key
    for pattern, repl in regex_translations:
        html = re.sub(pattern, repl, html)

    return html


def _m_to_wan(m, template):
    """Convert a captured '3.9' (millions) into '390' (万) inside template."""
    wan = round(float(m.group(1)) * 100)
    return template.format(wan=wan)


# ─── Translation tables ──────────────────────────────────────────────────────
# Format: list of (english_string, translated_string) tuples.
# Keys must be EXACT matches to strings in the generated public/index.html.
# Data strings (company names, dates, notes, URLs) are intentionally omitted.

ZH_HANS = [
    # <title> and meta description
    ("AI Layoff Tracker - Global Warning", "AI裁员追踪 - 全球警告"),
    ("Tracking job losses directly attributed to AI since GPT-4 launched. The iceberg behind the 2.9M total announced U.S. cuts. Updated daily.",
     "追踪自GPT-4发布以来直接归因于AI的工作岗位流失。隐藏在290万美国总裁员数背后的冰山。每日更新。"),
    # header
    ("&#9888;&#65039; AI Layoff Warning", "&#9888;&#65039; AI裁员警告"),
    ("Community-verified &middot; sourced by public news announcements &middot; since GPT-4 launch (March 14, 2023)",
     "社区验证 &middot; 来源于公开新闻报道 &middot; 自GPT-4发布（2023年3月14日）"),
    # doomsday hero
    ('<div class="dd-live-badge"><span class="dd-live-dot"></span>LIVE</div>',
     '<div class="dd-live-badge"><span class="dd-live-dot"></span>实时</div>'),
    ('<div class="dd-label">JOBS LOST DIRECTLY TO AI</div>',
     '<div class="dd-label">直接因AI失去的工作岗位</div>'),
    ("scroll to see the full picture", "向下滚动查看全貌"),
    # progress bar
    ("target: 30M by 2028", "目标：2028年达3000万"),
    # projection
    ("&#9888; The Forecast &mdash; McKinsey Global Institute &middot; Goldman Sachs",
     "&#9888; 预测 &mdash; 麦肯锡全球研究院 &middot; 高盛"),
    ("U.S. jobs significantly disrupted by AI &mdash; by 2028", "2028年前受AI显著冲击的美国工作岗位"),
    ("McKinsey: 40&ndash;50M Americans forced to shift roles by 2030",
     "麦肯锡：2030年前4000-5000万美国人被迫转岗"),
    ("Goldman Sachs: 2 in 3 U.S. jobs have meaningful AI exposure",
     "高盛：3分之2的美国工作有实质AI风险"),
    ("160M total U.S. workers", "美国劳动力总计1.6亿"),
    ("U.S. jobs have meaningful<br>AI exposure (Goldman Sachs)",
     "美国工作有实质<br>AI风险（高盛）"),
    ("of all U.S. work hours<br>automatable by 2030 (McKinsey)",
     "美国工作时间<br>到2030年可自动化（麦肯锡）"),
    ("two years away &mdash;<br>the inflection point", "还有两年 &mdash;<br>拐点已至"),
    # stat blocks
    ("PUBLIC FEAR SCORE", "公众恐惧指数"),
    ("net favorability (NBC, Mar 2026)", "净支持率（NBC，2026年3月）"),
    ("57% say risks outweigh benefits", "57%认为风险大于收益"),
    ("scale: -100 to +100", "范围：-100到+100"),
    ("JOBS LOST DIRECTLY TO AI", "直接因AI流失的岗位"),
    ("since GPT-4 launch", "自GPT-4发布"),
    ("JOBS PER UNEMPLOYED PERSON", "每名失业者对应职位数"),
    ("first time below 1.0 since pandemic (BLS, 2026)", "疫情以来首次低于1.0（BLS，2026）"),
    ("6.9M openings &nbsp;·&nbsp; 7.6M unemployed &nbsp;·&nbsp; more seekers than jobs",
     "690万职位空缺 &nbsp;·&nbsp; 760万失业者 &nbsp;·&nbsp; 求职者多于职位"),
    ("WORKFORCE NOW FREELANCING", "自由职业者占劳动力比例"),
    ("57M Americans in gig economy (2025) &mdash; up from 27% in 2016",
     "5700万美国人从事零工经济（2025）—— 较2016年27%上升"),
    ("Projected 50%+ by 2027 &nbsp;·&nbsp; avg rideshare pay: $9.09/hr after costs",
     "预计2027年超过50% &nbsp;·&nbsp; 网约车扣除成本后平均时薪9.09美元"),
    # iceberg
    ("The Iceberg &mdash; Jan 2023 to Today", "冰山 &mdash; 2023年1月至今"),
    ("AI-attributed (our tracker)", "AI归因（本追踪）"),
    ("All announced U.S. cuts, all reasons", "所有已公告美国裁员，所有原因"),
    ("Actual involuntary separations, BLS JOLTS", "实际非自愿离职，美国劳工统计局"),
    ("The 6.7x Inference", "6.7倍推断"),
    # acceleration
    ("<h2>The Acceleration</h2>", "<h2>加速</h2>"),
    ("AI-attributed job losses by year &mdash; our tracker (global, all publicly documented events)",
     "各年AI归因工作流失 &mdash; 本追踪（全球，所有公开记录事件）"),
    ("2026 is on pace for ~257,000", "2026年有望达到约257,000"),
    # jobs section
    ("<h2>So Where Are the New Jobs?</h2>", "<h2>那新增工作岗位在哪里？</h2>"),
    ("The verdict no one said out loud:", "没人说出口的裁决："),
    ("<h3>&#9650; Gaining</h3>", "<h3>&#9650; 增长</h3>"),
    ("<h3>&#9660; Losing</h3>", "<h3>&#9660; 萎缩</h3>"),
    # voices
    ("<h2>They All See It</h2>", "<h2>他们都看到了</h2>"),
    ("World leaders, economists, and the people building it &mdash; all saying the same thing.",
     "世界领袖、经济学家和技术建造者——都在说同样的话。"),
    ("He was right.", "他是对的。"),
    # evisceration
    ("<h2>The Invisible Flood: White-Collar Evisceration</h2>", "<h2>隐形洪水：白领岗位蒸发</h2>"),
    ("The numbers above only capture public layoff announcements. The quiet displacement &mdash; attrition, contracts not renewed, roles automated away &mdash; never makes the news.",
     "上述数据仅涵盖公开裁员公告。悄然发生的替代——自然减员、合同不续签、岗位被自动化——从未登上新闻。"),
    # CTA
    ("The data is in. The flood is real.", "数据已出。洪水是真实的。"),
    ("We don&#39;t have to argue about whether AI is taking jobs.<br>We can prove it. Now what?",
     "我们不必再争论AI是否在抢工作。<br>我们能证明。那下一步呢？"),
    ("We don&apos;t have to argue about whether AI is taking jobs.<br>We can prove it. Now what?",
     "我们不必再争论AI是否在抢工作。<br>我们能证明。那下一步呢？"),
    ("The question is no longer", "问题不再是"),
    ("it&#39;s", "而是"),
    ("it&apos;s", "而是"),
    ("what next.", "下一步怎么办。"),
    ("We believe the answer is redesigning work for human flourishing:", "我们相信答案是重新设计工作以促进人类繁荣："),
    ("not fighting the wave, but learning to navigate it.", "不是与浪潮抗争，而是学会驾驭它。"),
    ("Eudy&#39;s mission:", "Eudy的使命："),
    ("Eudy&apos;s mission:", "Eudy的使命："),
    ("Standardize work for human flourishing in the age of AI.", "在AI时代标准化工作以实现人类繁荣。"),
    ("Learn to navigate it &rarr;", "学习驾驭它 &rarr;"),
    ("Follow the journey", "关注旅程"),
    # events table
    ("<h2>Events</h2>", "<h2>事件记录</h2>"),
    (">Most Recent<", ">最近<"),
    (">Largest<", ">最大<"),
    (">All<", ">全部<"),
    (">Confirmed<", ">已确认<"),
    (">Likely<", ">很可能<"),
    ('placeholder="Search company..."', 'placeholder="搜索公司..."'),
    ("<th>Date</th>", "<th>日期</th>"),
    ("<th>Company</th>", "<th>公司</th>"),
    ("<th>Headcount</th>", "<th>裁员人数</th>"),
    ("<th>Attribution</th>", "<th>归因</th>"),
    ("<th>Source</th>", "<th>来源</th>"),
    # submit
    ("<h2>Did we miss one?</h2>", "<h2>我们遗漏了吗？</h2>"),
    ('placeholder="Company name *"', 'placeholder="公司名称 *"'),
    ('placeholder="Headcount *"', 'placeholder="裁员人数 *"'),
    ('placeholder="Source URL *"', 'placeholder="来源链接 *"'),
    ('placeholder="Notes (optional', 'placeholder="备注（可选'),
    ('placeholder="Your email (optional', 'placeholder="您的邮箱（可选'),
    ("Submit &rarr;", "提交 &rarr;"),
    ("Thanks &mdash; we&#39;ll verify it.", "谢谢——我们会核实的。"),
    ("Thanks &mdash; we&apos;ll verify it.", "谢谢——我们会核实的。"),
    ("Verified submissions go live within 24 hours. While you wait &mdash; follow the mission.",
     "经验证的提交将在24小时内上线。在等待期间——关注我们的使命。"),
    ("Follow @muhan.being on Instagram", "在Instagram关注 @muhan.being"),
    # methodology
    ("<h3>Methodology</h3>", "<h3>研究方法</h3>"),
    ("<strong>confirmed</strong> = Company explicitly stated AI/automation as the reason for layoffs",
     "<strong>已确认</strong> = 公司明确表示AI/自动化是裁员原因"),
    ("<strong>likely</strong> = Company investing heavily in AI while cutting jobs, or media analysis attributes cuts to AI",
     "<strong>很可能</strong> = 公司在裁员的同时大力投资AI，或媒体分析将裁员归因于AI"),
    ("<strong>unclear</strong> = Tech company layoffs that may be related to AI transformation but not explicitly stated",
     "<strong>不明确</strong> = 科技公司裁员可能与AI转型有关但未明确说明"),
    ("This page is updated daily.", "本页面每日更新。"),
    ("Why the real number is much higher:", "为何真实数字要高得多："),
    ("Our tracker captures only public announcements. The majority of AI displacement happens invisibly &mdash;",
     "我们的追踪仅记录公开公告。大多数AI取代是无形发生的——"),
    ("through attrition, contract non-renewals, and quiet eliminations never reported in the press.",
     "通过自然减员、合同不续签以及从未见报的悄然裁员。"),
    ("The real number is far larger.", "真实数字要大得多。"),
    # footer
    ("Updated daily &middot;", "每日更新 &middot;"),
    ("GitHub source &amp; full dataset", "GitHub源码及完整数据"),
    ("Data is for informational purposes only. Not investment or employment advice.",
     "数据仅供参考，不构成投资或就业建议。"),
    # JS
    (">No results</td>", ">暂无结果</td>"),
    ("+ ' events'", "+ ' 个事件'"),
    ("'Submitting...'", "'提交中...'"),
    ("'Submit →'", "'提交 →'"),
    ("'Something went wrong. Please try again.'", "'出错了，请重试。'"),
    ("' per day'", "' 个/天'"),
]

ZH_HANT = [
    ("AI Layoff Tracker - Global Warning", "AI裁員追蹤 - 全球警告"),
    ("Tracking job losses directly attributed to AI since GPT-4 launched. The iceberg behind the 2.9M total announced U.S. cuts. Updated daily.",
     "追蹤自GPT-4發布以來直接歸因於AI的工作崗位流失。隱藏在290萬美國總裁員數背後的冰山。每日更新。"),
    ("&#9888;&#65039; AI Layoff Warning", "&#9888;&#65039; AI裁員警告"),
    ("Community-verified &middot; sourced by public news announcements &middot; since GPT-4 launch (March 14, 2023)",
     "社群驗證 &middot; 來源於公開新聞報導 &middot; 自GPT-4發布（2023年3月14日）"),
    ('<div class="dd-live-badge"><span class="dd-live-dot"></span>LIVE</div>',
     '<div class="dd-live-badge"><span class="dd-live-dot"></span>即時</div>'),
    ('<div class="dd-label">JOBS LOST DIRECTLY TO AI</div>',
     '<div class="dd-label">直接因AI失去的工作崗位</div>'),
    ("scroll to see the full picture", "向下捲動查看全貌"),
    ("target: 30M by 2028", "目標：2028年達3000萬"),
    ("&#9888; The Forecast &mdash; McKinsey Global Institute &middot; Goldman Sachs",
     "&#9888; 預測 &mdash; 麥肯錫全球研究院 &middot; 高盛"),
    ("U.S. jobs significantly disrupted by AI &mdash; by 2028", "2028年前受AI顯著衝擊的美國工作崗位"),
    ("McKinsey: 40&ndash;50M Americans forced to shift roles by 2030",
     "麥肯錫：2030年前4000-5000萬美國人被迫轉崗"),
    ("Goldman Sachs: 2 in 3 U.S. jobs have meaningful AI exposure",
     "高盛：3分之2的美國工作有實質AI風險"),
    ("160M total U.S. workers", "美國勞動力總計1.6億"),
    ("U.S. jobs have meaningful<br>AI exposure (Goldman Sachs)",
     "美國工作有實質<br>AI風險（高盛）"),
    ("of all U.S. work hours<br>automatable by 2030 (McKinsey)",
     "美國工作時間<br>到2030年可自動化（麥肯錫）"),
    ("two years away &mdash;<br>the inflection point", "還有兩年 &mdash;<br>拐點已至"),
    ("PUBLIC FEAR SCORE", "公眾恐懼指數"),
    ("net favorability (NBC, Mar 2026)", "淨支持率（NBC，2026年3月）"),
    ("57% say risks outweigh benefits", "57%認為風險大於收益"),
    ("scale: -100 to +100", "範圍：-100到+100"),
    ("JOBS LOST DIRECTLY TO AI", "直接因AI流失的崗位"),
    ("since GPT-4 launch", "自GPT-4發布"),
    ("JOBS PER UNEMPLOYED PERSON", "每名失業者對應職位數"),
    ("first time below 1.0 since pandemic (BLS, 2026)", "疫情以來首次低於1.0（BLS，2026）"),
    ("6.9M openings &nbsp;·&nbsp; 7.6M unemployed &nbsp;·&nbsp; more seekers than jobs",
     "690萬職位空缺 &nbsp;·&nbsp; 760萬失業者 &nbsp;·&nbsp; 求職者多於職位"),
    ("WORKFORCE NOW FREELANCING", "自由工作者佔勞動力比例"),
    ("57M Americans in gig economy (2025) &mdash; up from 27% in 2016",
     "5700萬美國人從事零工經濟（2025）—— 較2016年27%上升"),
    ("Projected 50%+ by 2027 &nbsp;·&nbsp; avg rideshare pay: $9.09/hr after costs",
     "預計2027年超過50% &nbsp;·&nbsp; 網約車扣除成本後平均時薪9.09美元"),
    ("The Iceberg &mdash; Jan 2023 to Today", "冰山 &mdash; 2023年1月至今"),
    ("AI-attributed (our tracker)", "AI歸因（本追蹤）"),
    ("All announced U.S. cuts, all reasons", "所有已公告美國裁員，所有原因"),
    ("Actual involuntary separations, BLS JOLTS", "實際非自願離職，美國勞工統計局"),
    ("The 6.7x Inference", "6.7倍推斷"),
    ("<h2>The Acceleration</h2>", "<h2>加速</h2>"),
    ("AI-attributed job losses by year &mdash; our tracker (global, all publicly documented events)",
     "各年AI歸因工作流失 &mdash; 本追蹤（全球，所有公開記錄事件）"),
    ("2026 is on pace for ~257,000", "2026年有望達到約257,000"),
    ("<h2>So Where Are the New Jobs?</h2>", "<h2>那新增工作崗位在哪裡？</h2>"),
    ("The verdict no one said out loud:", "沒人說出口的裁決："),
    ("<h3>&#9650; Gaining</h3>", "<h3>&#9650; 增長</h3>"),
    ("<h3>&#9660; Losing</h3>", "<h3>&#9660; 萎縮</h3>"),
    ("<h2>They All See It</h2>", "<h2>他們都看到了</h2>"),
    ("World leaders, economists, and the people building it &mdash; all saying the same thing.",
     "世界領袖、經濟學家和技術建造者——都在說同樣的話。"),
    ("He was right.", "他是對的。"),
    ("<h2>The Invisible Flood: White-Collar Evisceration</h2>", "<h2>隱形洪水：白領崗位蒸發</h2>"),
    ("The numbers above only capture public layoff announcements. The quiet displacement &mdash; attrition, contracts not renewed, roles automated away &mdash; never makes the news.",
     "上述數據僅涵蓋公開裁員公告。悄然發生的替代——自然減員、合約不續簽、崗位被自動化——從未登上新聞。"),
    ("The data is in. The flood is real.", "數據已出。洪水是真實的。"),
    ("We don&#39;t have to argue about whether AI is taking jobs.<br>We can prove it. Now what?",
     "我們不必再爭論AI是否在搶工作。<br>我們能證明。那下一步呢？"),
    ("We don&apos;t have to argue about whether AI is taking jobs.<br>We can prove it. Now what?",
     "我們不必再爭論AI是否在搶工作。<br>我們能證明。那下一步呢？"),
    ("We believe the answer is redesigning work for human flourishing:", "我們相信答案是重新設計工作以促進人類繁榮："),
    ("not fighting the wave, but learning to navigate it.", "不是與浪潮抗爭，而是學會駕馭它。"),
    ("Eudy&#39;s mission:", "Eudy的使命："),
    ("Eudy&apos;s mission:", "Eudy的使命："),
    ("Standardize work for human flourishing in the age of AI.", "在AI時代標準化工作以實現人類繁榮。"),
    ("Learn to navigate it &rarr;", "學習駕馭它 &rarr;"),
    ("Follow the journey", "關注旅程"),
    ("<h2>Events</h2>", "<h2>事件記錄</h2>"),
    (">Most Recent<", ">最近<"),
    (">Largest<", ">最大<"),
    (">All<", ">全部<"),
    (">Confirmed<", ">已確認<"),
    (">Likely<", ">很可能<"),
    ('placeholder="Search company..."', 'placeholder="搜尋公司..."'),
    ("<th>Date</th>", "<th>日期</th>"),
    ("<th>Company</th>", "<th>公司</th>"),
    ("<th>Headcount</th>", "<th>裁員人數</th>"),
    ("<th>Attribution</th>", "<th>歸因</th>"),
    ("<th>Source</th>", "<th>來源</th>"),
    ("<h2>Did we miss one?</h2>", "<h2>我們遺漏了嗎？</h2>"),
    ('placeholder="Company name *"', 'placeholder="公司名稱 *"'),
    ('placeholder="Headcount *"', 'placeholder="裁員人數 *"'),
    ('placeholder="Source URL *"', 'placeholder="來源連結 *"'),
    ('placeholder="Notes (optional', 'placeholder="備註（可選'),
    ('placeholder="Your email (optional', 'placeholder="您的郵箱（可選'),
    ("Submit &rarr;", "提交 &rarr;"),
    ("Thanks &mdash; we&#39;ll verify it.", "謝謝——我們會核實的。"),
    ("Thanks &mdash; we&apos;ll verify it.", "謝謝——我們會核實的。"),
    ("Verified submissions go live within 24 hours. While you wait &mdash; follow the mission.",
     "經驗證的提交將在24小時內上線。在等待期間——關注我們的使命。"),
    ("Follow @muhan.being on Instagram", "在Instagram關注 @muhan.being"),
    ("<h3>Methodology</h3>", "<h3>研究方法</h3>"),
    ("<strong>confirmed</strong> = Company explicitly stated AI/automation as the reason for layoffs",
     "<strong>已確認</strong> = 公司明確表示AI/自動化是裁員原因"),
    ("<strong>likely</strong> = Company investing heavily in AI while cutting jobs, or media analysis attributes cuts to AI",
     "<strong>很可能</strong> = 公司在裁員的同時大力投資AI，或媒體分析將裁員歸因於AI"),
    ("<strong>unclear</strong> = Tech company layoffs that may be related to AI transformation but not explicitly stated",
     "<strong>不明確</strong> = 科技公司裁員可能與AI轉型有關但未明確說明"),
    ("This page is updated daily.", "本頁面每日更新。"),
    ("Why the real number is much higher:", "為何真實數字要高得多："),
    ("Our tracker captures only public announcements. The majority of AI displacement happens invisibly &mdash;",
     "我們的追蹤僅記錄公開公告。大多數AI取代是無形發生的——"),
    ("through attrition, contract non-renewals, and quiet eliminations never reported in the press.",
     "通過自然減員、合約不續簽以及從未見報的悄然裁員。"),
    ("The real number is far larger.", "真實數字要大得多。"),
    ("Updated daily &middot;", "每日更新 &middot;"),
    ("GitHub source &amp; full dataset", "GitHub源碼及完整數據"),
    ("Data is for informational purposes only. Not investment or employment advice.",
     "數據僅供參考，不構成投資或就業建議。"),
    (">No results</td>", ">暫無結果</td>"),
    ("+ ' events'", "+ ' 個事件'"),
    ("'Submitting...'", "'提交中...'"),
    ("'Submit →'", "'提交 →'"),
    ("'Something went wrong. Please try again.'", "'出錯了，請重試。'"),
    ("' per day'", "' 個/天'"),
]

ES = [
    ("AI Layoff Tracker - Global Warning", "Rastreador de Despidos por IA - Alerta Global"),
    ("Tracking job losses directly attributed to AI since GPT-4 launched. The iceberg behind the 2.9M total announced U.S. cuts. Updated daily.",
     "Rastreando pérdidas de empleos directamente atribuidas a la IA desde el lanzamiento de GPT-4. El iceberg detrás de los 2.9M de recortes anunciados en EE.UU. Actualizado diariamente."),
    ("&#9888;&#65039; AI Layoff Warning", "&#9888;&#65039; Alerta de Despidos por IA"),
    ("Community-verified &middot; sourced by public news announcements &middot; since GPT-4 launch (March 14, 2023)",
     "Verificado por la comunidad &middot; basado en anuncios de noticias públicas &middot; desde el lanzamiento de GPT-4 (14 de marzo de 2023)"),
    ('<div class="dd-live-badge"><span class="dd-live-dot"></span>LIVE</div>',
     '<div class="dd-live-badge"><span class="dd-live-dot"></span>EN VIVO</div>'),
    ('<div class="dd-label">JOBS LOST DIRECTLY TO AI</div>',
     '<div class="dd-label">EMPLEOS PERDIDOS DIRECTAMENTE POR IA</div>'),
    ("scroll to see the full picture", "desplázate para ver el panorama completo"),
    ("target: 30M by 2028", "objetivo: 30M para 2028"),
    ("&#9888; The Forecast &mdash; McKinsey Global Institute &middot; Goldman Sachs",
     "&#9888; El Pronóstico &mdash; McKinsey Global Institute &middot; Goldman Sachs"),
    ("U.S. jobs significantly disrupted by AI &mdash; by 2028",
     "empleos en EE.UU. significativamente afectados por IA &mdash; para 2028"),
    ("McKinsey: 40&ndash;50M Americans forced to shift roles by 2030",
     "McKinsey: 40–50M de americanos forzados a cambiar de rol para 2030"),
    ("Goldman Sachs: 2 in 3 U.S. jobs have meaningful AI exposure",
     "Goldman Sachs: 2 de cada 3 empleos en EE.UU. tienen exposición significativa a IA"),
    ("160M total U.S. workers", "160M trabajadores en EE.UU."),
    ("U.S. jobs have meaningful<br>AI exposure (Goldman Sachs)",
     "empleos en EE.UU. con<br>exposición significativa a IA (Goldman Sachs)"),
    ("of all U.S. work hours<br>automatable by 2030 (McKinsey)",
     "de todas las horas de trabajo<br>automatizables para 2030 (McKinsey)"),
    ("two years away &mdash;<br>the inflection point", "a dos años de distancia &mdash;<br>el punto de inflexión"),
    ("PUBLIC FEAR SCORE", "ÍNDICE DE TEMOR PÚBLICO"),
    ("net favorability (NBC, Mar 2026)", "favorabilidad neta (NBC, mar. 2026)"),
    ("57% say risks outweigh benefits", "57% dice que los riesgos superan los beneficios"),
    ("scale: -100 to +100", "escala: -100 a +100"),
    ("JOBS LOST DIRECTLY TO AI", "EMPLEOS PERDIDOS DIRECTAMENTE POR IA"),
    ("since GPT-4 launch", "desde el lanzamiento de GPT-4"),
    ("JOBS PER UNEMPLOYED PERSON", "EMPLEOS POR PERSONA DESEMPLEADA"),
    ("first time below 1.0 since pandemic (BLS, 2026)", "primera vez por debajo de 1.0 desde la pandemia (BLS, 2026)"),
    ("6.9M openings &nbsp;·&nbsp; 7.6M unemployed &nbsp;·&nbsp; more seekers than jobs",
     "6.9M vacantes &nbsp;·&nbsp; 7.6M desempleados &nbsp;·&nbsp; más buscadores que empleos"),
    ("WORKFORCE NOW FREELANCING", "FUERZA LABORAL EN TRABAJO INDEPENDIENTE"),
    ("57M Americans in gig economy (2025) &mdash; up from 27% in 2016",
     "57M de americanos en economía gig (2025) &mdash; desde 27% en 2016"),
    ("Projected 50%+ by 2027 &nbsp;·&nbsp; avg rideshare pay: $9.09/hr after costs",
     "Proyectado 50%+ para 2027 &nbsp;·&nbsp; pago promedio de rideshare: $9.09/hr después de costos"),
    ("The Iceberg &mdash; Jan 2023 to Today", "El Iceberg &mdash; Enero 2023 hasta Hoy"),
    ("AI-attributed (our tracker)", "Atribuido a IA (nuestro rastreador)"),
    ("All announced U.S. cuts, all reasons", "Todos los recortes anunciados en EE.UU., todas las razones"),
    ("Actual involuntary separations, BLS JOLTS", "Separaciones involuntarias reales, BLS JOLTS"),
    ("The 6.7x Inference", "La Inferencia 6.7×"),
    ("<h2>The Acceleration</h2>", "<h2>La Aceleración</h2>"),
    ("AI-attributed job losses by year &mdash; our tracker (global, all publicly documented events)",
     "Pérdidas de empleos atribuidas a IA por año &mdash; nuestro rastreador (global, todos los eventos documentados públicamente)"),
    ("2026 is on pace for ~257,000", "2026 va camino a ~257,000"),
    ("<h2>So Where Are the New Jobs?</h2>", "<h2>¿Y dónde están los nuevos empleos?</h2>"),
    ("The verdict no one said out loud:", "El veredicto que nadie dijo en voz alta:"),
    ("<h3>&#9650; Gaining</h3>", "<h3>&#9650; Ganando</h3>"),
    ("<h3>&#9660; Losing</h3>", "<h3>&#9660; Perdiendo</h3>"),
    ("<h2>They All See It</h2>", "<h2>Todos Lo Ven</h2>"),
    ("World leaders, economists, and the people building it &mdash; all saying the same thing.",
     "Líderes mundiales, economistas y los que lo construyen &mdash; todos diciendo lo mismo."),
    ("He was right.", "Tenía razón."),
    ("<h2>The Invisible Flood: White-Collar Evisceration</h2>",
     "<h2>La Inundación Invisible: Evisceración de Empleos de Oficina</h2>"),
    ("The numbers above only capture public layoff announcements. The quiet displacement &mdash; attrition, contracts not renewed, roles automated away &mdash; never makes the news.",
     "Las cifras anteriores solo capturan anuncios públicos de despidos. El desplazamiento silencioso &mdash; desgaste natural, contratos no renovados, roles automatizados &mdash; nunca llega a las noticias."),
    ("The data is in. The flood is real.", "Los datos están. La inundación es real."),
    ("We don&#39;t have to argue about whether AI is taking jobs.<br>We can prove it. Now what?",
     "No tenemos que debatir si la IA está quitando empleos.<br>Podemos probarlo. ¿Y ahora qué?"),
    ("We don&apos;t have to argue about whether AI is taking jobs.<br>We can prove it. Now what?",
     "No tenemos que debatir si la IA está quitando empleos.<br>Podemos probarlo. ¿Y ahora qué?"),
    ("We believe the answer is redesigning work for human flourishing:",
     "Creemos que la respuesta es rediseñar el trabajo para el florecimiento humano:"),
    ("not fighting the wave, but learning to navigate it.",
     "no luchar contra la ola, sino aprender a navegarla."),
    ("Eudy&#39;s mission:", "La misión de Eudy:"),
    ("Eudy&apos;s mission:", "La misión de Eudy:"),
    ("Standardize work for human flourishing in the age of AI.",
     "Estandarizar el trabajo para el florecimiento humano en la era de la IA."),
    ("Learn to navigate it &rarr;", "Aprende a navegarlo &rarr;"),
    ("Follow the journey", "Sigue el camino"),
    ("<h2>Events</h2>", "<h2>Eventos</h2>"),
    (">Most Recent<", ">Más reciente<"),
    (">Largest<", ">Más grande<"),
    (">All<", ">Todos<"),
    (">Confirmed<", ">Confirmado<"),
    (">Likely<", ">Probable<"),
    ('placeholder="Search company..."', 'placeholder="Buscar empresa..."'),
    ("<th>Date</th>", "<th>Fecha</th>"),
    ("<th>Company</th>", "<th>Empresa</th>"),
    ("<th>Headcount</th>", "<th>Empleados cortados</th>"),
    ("<th>Attribution</th>", "<th>Atribución</th>"),
    ("<th>Source</th>", "<th>Fuente</th>"),
    ("<h2>Did we miss one?</h2>", "<h2>¿Nos perdimos uno?</h2>"),
    ('placeholder="Company name *"', 'placeholder="Nombre de la empresa *"'),
    ('placeholder="Headcount *"', 'placeholder="Número de empleados *"'),
    ('placeholder="Source URL *"', 'placeholder="URL de la fuente *"'),
    ('placeholder="Notes (optional', 'placeholder="Notas (opcional'),
    ('placeholder="Your email (optional', 'placeholder="Tu correo (opcional'),
    ("Submit &rarr;", "Enviar &rarr;"),
    ("Thanks &mdash; we&#39;ll verify it.", "Gracias &mdash; lo verificaremos."),
    ("Thanks &mdash; we&apos;ll verify it.", "Gracias &mdash; lo verificaremos."),
    ("Verified submissions go live within 24 hours. While you wait &mdash; follow the mission.",
     "Las entradas verificadas se publican en 24 horas. Mientras esperas &mdash; sigue la misión."),
    ("Follow @muhan.being on Instagram", "Sigue @muhan.being en Instagram"),
    ("<h3>Methodology</h3>", "<h3>Metodología</h3>"),
    ("<strong>confirmed</strong> = Company explicitly stated AI/automation as the reason for layoffs",
     "<strong>confirmado</strong> = La empresa declaró explícitamente la IA/automatización como razón de los despidos"),
    ("<strong>likely</strong> = Company investing heavily in AI while cutting jobs, or media analysis attributes cuts to AI",
     "<strong>probable</strong> = La empresa invierte fuertemente en IA mientras recorta empleos, o el análisis de medios atribuye los recortes a la IA"),
    ("<strong>unclear</strong> = Tech company layoffs that may be related to AI transformation but not explicitly stated",
     "<strong>poco claro</strong> = Despidos en empresas tecnológicas que pueden estar relacionados con la transformación de IA pero no se indica explícitamente"),
    ("This page is updated daily.", "Esta página se actualiza diariamente."),
    ("Why the real number is much higher:", "Por qué el número real es mucho mayor:"),
    ("Our tracker captures only public announcements. The majority of AI displacement happens invisibly &mdash;",
     "Nuestro rastreador solo captura anuncios públicos. La mayoría del desplazamiento por IA ocurre de forma invisible &mdash;"),
    ("through attrition, contract non-renewals, and quiet eliminations never reported in the press.",
     "a través del desgaste natural, no renovación de contratos y eliminaciones silenciosas nunca reportadas en la prensa."),
    ("The real number is far larger.", "El número real es mucho mayor."),
    ("Updated daily &middot;", "Actualizado diariamente &middot;"),
    ("GitHub source &amp; full dataset", "Código fuente en GitHub y conjunto de datos completo"),
    ("Data is for informational purposes only. Not investment or employment advice.",
     "Los datos son solo para fines informativos. No son asesoramiento de inversión ni laboral."),
    (">No results</td>", ">Sin resultados</td>"),
    ("+ ' events'", "+ ' eventos'"),
    ("'Submitting...'", "'Enviando...'"),
    ("'Submit →'", "'Enviar →'"),
    ("'Something went wrong. Please try again.'", "'Algo salió mal. Por favor, inténtalo de nuevo.'"),
    ("' per day'", "' por día'"),
]


# ─── Regex translation tables ────────────────────────────────────────────────
# For UI strings that embed numbers regenerated daily by generate_page.py
# (total_confirmed, avg_per_day, pct_toward_30m, estimated_millions).
# NEVER add these as exact-match strings above — the number changes every day
# and the key silently stops matching (this froze the i18n pages at launch
# values until 2026-08). Capture the number and re-insert it instead.

ZH_HANS_RE = [
    (r"est\. true AI impact via 6\.7&times; multiplier: ~([\d.]+)M",
     lambda m: _m_to_wan(m, "通过6.7倍乘数估算的真实AI影响：约{wan}万")),
    (r"([\d,]+) confirmed</span>", r"\1 已确认</span>"),
    (r"([\d.]+)% toward 30M by 2028", r"已达2028年3000万目标的\1%"),
    (r"documented &times; 6\.7 unlabeled multiplier = ~([\d.]+)M estimated",
     lambda m: _m_to_wan(m, "已记录 &times; 6.7未标注乘数 = 约{wan}万估算")),
    (r"confirmed &nbsp;·&nbsp; ~([\d,]+)/day", r"已确认 &nbsp;·&nbsp; 约\1/天"),
]

ZH_HANT_RE = [
    (r"est\. true AI impact via 6\.7&times; multiplier: ~([\d.]+)M",
     lambda m: _m_to_wan(m, "通過6.7倍乘數估算的真實AI影響：約{wan}萬")),
    (r"([\d,]+) confirmed</span>", r"\1 已確認</span>"),
    (r"([\d.]+)% toward 30M by 2028", r"已達2028年3000萬目標的\1%"),
    (r"documented &times; 6\.7 unlabeled multiplier = ~([\d.]+)M estimated",
     lambda m: _m_to_wan(m, "已記錄 &times; 6.7未標注乘數 = 約{wan}萬估算")),
    (r"confirmed &nbsp;·&nbsp; ~([\d,]+)/day", r"已確認 &nbsp;·&nbsp; 約\1/天"),
]

ES_RE = [
    (r"est\. true AI impact via 6\.7&times; multiplier: ~([\d.]+)M",
     r"impacto real estimado de IA con multiplicador 6.7×: ~\1M"),
    (r"([\d,]+) confirmed</span>", r"\1 confirmados</span>"),
    (r"([\d.]+)% toward 30M by 2028", r"\1% hacia 30M para 2028"),
    (r"documented &times; 6\.7 unlabeled multiplier = ~([\d.]+)M estimated",
     r"documentados &times; multiplicador 6.7 sin etiquetar = ~\1M estimados"),
    (r"confirmed &nbsp;·&nbsp; ~([\d,]+)/day", r"confirmados &nbsp;·&nbsp; ~\1/día"),
]


# ─── Main ────────────────────────────────────────────────────────────────────

def main():
    src = "public/index.html"
    if not os.path.exists(src):
        print(f"ERROR: {src} not found. Run generate_page.py first.")
        return

    with open(src, "r", encoding="utf-8") as f:
        base = f.read()

    targets = [
        ("public/zh-hans/index.html", "zh-hans", "zh-Hans", ZH_HANS, ZH_HANS_RE),
        ("public/zh-hant/index.html", "zh-hant", "zh-Hant", ZH_HANT, ZH_HANT_RE),
        ("public/es/index.html",       "es",       "es",      ES,      ES_RE),
    ]

    for out_path, lang_code, lang_attr, translations, regex_translations in targets:
        os.makedirs(os.path.dirname(out_path), exist_ok=True)
        result = transform(base, lang_code, lang_attr, translations, regex_translations)
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(result)
        print(f"Generated: {out_path}")

    print("\nAll translated pages generated.")
    print("Remember: company names, dates, and notes stay in English by design.")


if __name__ == "__main__":
    main()
